// ===== 1024 COLLECTION — MUSEUM-GRADE DATABASE =====
// Compiled from Heritage Auctions, Stack's Bowers, Beijing ChengXuan,
// China Guardian, PCGS Population Reports, ShouXi.com, ArtHitParade

// ===== COIN DATABASE (100+ entries) =====
const COINS = [
  // ─── TIER 0: SUPREME RARITIES (>30M RMB) ───
  {
    id:"C001", cat:"qing-tael",
    cn:"广东省造光绪元宝寿字双龙壹两",
    en:"Kwangtung Longevity Double Dragon One Tael",
    img:["img/C001_shou_closeup.jpg","img/C001_obverse_reverse.jpg","img/C001_reverse_closeup.jpg"],
    era:"清·光绪", year:"c.1890", mint:"广东造币厂（喜敦机器）",
    mintEn:"Kwangtung Mint (Heaton machinery)",
    metal:"银 Silver", weight:"37.3g", diam:"39mm",
    rarity: 10, tier: 0,
    pcgs_pop: { total:5, sp:0, xf:0, au:0, ms60:0, ms61:0, ms62:0, ms63:0, ms64:1, ms65:0, ms66:0, ms67:0 },
    history_cn:"中国机制银圆之王。光绪年间广东造币厂试铸，正面「寿」字居中，双龙拱卫，寓意龙腾献寿。未正式发行，存世极罕，已知评级仅5枚。",
    history_en:"The supreme rarity of Chinese milled silver. Trial strike at the Kwangtung Mint during Guangxu era. Never officially issued. Only 5 graded examples known.",
    auctions:[
      { date:"2022-08", house:"北京诚轩 ChengXuan", lot:"未公开", grade:"未评级", price_rmb:null, price_usd:null, note:"蔡先生委托泓盛，开价1500万" },
      { date:"2019-10", house:"Heritage Auctions", lot:"30152", grade:"NGC UNC Details", price_rmb:null, price_usd:24000, note:"Fantasy Tael (非原始壹两，价格参考)" },
      { date:"2019-08", house:"SBP Hong Kong", lot:"", grade:"PCGS AU Detail", price_rmb:null, price_usd:2400000, note:"Realized $2.4M hammer" },
    ],
    provenance:[
      { holder:"蔡先生（浙江）", grade:"", acquired:"~2010", price:"", status:"持有13年后委托泓盛", note:"出品人" },
      { holder:"林宪璋（台湾）", grade:"", acquired:"", price:"", status:"持有", note:"八枚一级币之一" },
      { holder:"张明全（台湾）", grade:"", acquired:"", price:"", status:"持有（阴蝙蝠版）", note:"藏而不宣" },
      { holder:"林张 / 上海博物馆", grade:"", acquired:"", price:"", status:"馆藏", note:"博物馆级参考" },
      { holder:"鸿禧美术馆", grade:"", acquired:"", price:"", status:"旧藏", note:"祥晋古泉来源" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"40,000,000+",
  },
  {
    id:"C002", cat:"qing-tael",
    cn:"奉天省造癸卯光绪元宝库平壹两",
    en:"Fengtian Guimao One Tael (1903)",
    era:"清·光绪廿九年", year:"1903", mint:"奉天机器局",
    mintEn:"Fengtian Arsenal Mint",
    metal:"银 Silver", weight:"37.3g", diam:"39mm",
    rarity: 10, tier: 0,
    pcgs_pop: { total:3 },
    history_cn:"中国银圆拍卖最高成交纪录保持者。光绪二十九年奉天机器局试铸壹两银圆，未发行。2022年诚轩拍卖以4657.5万元成交，创中国钱币拍卖历史纪录。",
    history_en:"Holds the all-time auction record for Chinese coins. Trial strike at Fengtian Arsenal in 1903. Sold for 46.575M RMB ($6.9M) at ChengXuan 2022, setting the all-time record.",
    auctions:[
      { date:"2022-08-12", house:"北京诚轩 ChengXuan", lot:"2562", grade:"PCGS SP63", price_rmb:46575000, price_usd:6900000, note:"中国银圆拍卖历史最高价" },
      { date:"2010", house:"北京诚轩", lot:"", grade:"", price_rmb:25300000, price_usd:null, note:"" },
    ],
    provenance:[],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"46,575,000 (record)",
  },
  // ─── TIER 1: MUSEUM GRADE (10-30M RMB) ───
  {
    id:"C003", cat:"qing-dragon",
    cn:"宣统三年大清银币壹圆（短须龙版）",
    en:"Hsuan Tung Year 3 Short Beard Dragon Dollar (1911)",
    era:"清·宣统三年", year:"1911", mint:"天津造币总厂",
    mintEn:"Tientsin Central Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 9, tier: 1,
    pcgs_pop: { total:6 },
    history_cn:"大清帝国最后的龙银样币之一。短须龙版为意大利雕刻师 Luigi Giorgi 设计的试铸版本，龙须短而有力，区别于长须龙。存世极罕。",
    history_en:"One of the last dragon dollar patterns of the Qing Empire. The Short Beard variety was designed by Italian engraver Luigi Giorgi. Extremely rare.",
    auctions:[
      { date:"2023-06", house:"Heritage Hong Kong", lot:"", grade:"PCGS SP64", price_rmb:null, price_usd:2800000, note:"" },
      { date:"2021-05", house:"北京诚轩", lot:"", grade:"PCGS SP63", price_rmb:5750000, price_usd:null, note:"短须龙春拍" },
    ],
    provenance:[
      { holder:"代旭翔（代大藏家）", grade:"", acquired:"", price:"", status:"持有", note:"官方，女儿不同姓沈" },
      { holder:"何代水（台湾）", grade:"", acquired:"", price:"", status:"持有", note:"芯片/IT行业" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"10,000,000+",
  },
  {
    id:"C004", cat:"qing-dragon",
    cn:"宣统三年大清银币壹圆（长须龙版）",
    en:"Hsuan Tung Year 3 Long Beard/Whisker Dragon Dollar (1911)",
    era:"清·宣统三年", year:"1911", mint:"天津造币总厂",
    mintEn:"Tientsin Central Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 8, tier: 1,
    pcgs_pop: { total:41, au55:2, au58:1, ms60:1, ms61:8, ms62:15, ms62p:2, ms63:3, ms63p:3, ms64:5, ms66:1 },
    history_cn:"宣三系列最著名的品种。长须龙设计精美，被誉为中国龙银设计的巅峰。2022年SBP以300万美元成交SP63+，创美国拍卖中国银圆纪录。",
    history_en:"The most celebrated variety in the Xuan Tong 3 series. The Long Whisker Dragon is considered the pinnacle of Chinese dragon dollar design. SBP 2022 realized $3M for SP63+, a US auction record for Chinese silver.",
    auctions:[
      { date:"2025-06-20", house:"Heritage HKINF", lot:"", grade:"NGC SP63", price_rmb:null, price_usd:504000, note:"Peh Family Collection (后铸)" },
      { date:"2025-06-20", house:"Heritage HKINF", lot:"", grade:"NGC SP63+", price_rmb:null, price_usd:408000, note:"Peh Family Collection (后铸)" },
      { date:"2025-05-04", house:"Stack's Bowers HK", lot:"", grade:"", price_rmb:null, price_usd:3000000, note:"长须龙 Record price" },
      { date:"2024-06", house:"Heritage HKINF", lot:"", grade:"NGC SP63", price_rmb:null, price_usd:690000, note:"当时创该品种拍卖纪录" },
      { date:"2023-12", house:"Heritage HKINF", lot:"", grade:"NGC SP64+", price_rmb:null, price_usd:630000, note:"Heritage $8.68M HKINF 领衔" },
      { date:"2022-05-04", house:"Stack's Bowers", lot:"51134", grade:"PCGS SP63+", price_rmb:21000000, price_usd:3000000, note:"美国拍卖中国银圆最高价" },
      { date:"2021-12", house:"Heritage HKINF", lot:"", grade:"", price_rmb:null, price_usd:1200000, note:"" },
      { date:"2021-11", house:"北京诚轩", lot:"", grade:"PCGS SP62", price_rmb:6727500, price_usd:null, note:"秋拍" },
      { date:"2021-05", house:"北京诚轩", lot:"", grade:"PCGS SP63", price_rmb:5750000, price_usd:null, note:"春拍" },
      { date:"2021-04", house:"Stack's Bowers", lot:"", grade:"PCGS SP64", price_rmb:null, price_usd:1020000, note:"Pinnacle Collection" },
    ],
    provenance:[
      { holder:"kent（杭州）", grade:"MS64?", acquired:"", price:"", status:"持有数枚", note:"" },
      { holder:"Peh Family（裴氏家族）", grade:"", acquired:"", price:"", status:"Heritage 2025出品", note:"Peh Family Collection Part III" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"5,000,000+",
  },
  {
    id:"C005", cat:"qing-tael",
    cn:"大清户部光绪元宝库平壹两",
    en:"Board of Revenue (Hu Bu) Guangxu One Tael",
    era:"清·光绪", year:"c.1903", mint:"天津户部造币总厂",
    mintEn:"Board of Revenue Mint, Tientsin",
    metal:"银 Silver", weight:"37.3g", diam:"39mm",
    rarity: 8, tier: 1,
    pcgs_pop: { total:16, au55:1, au58:1, ms62:8, ms63:2, ms63p:2, ms64:1, ms64p:1 },
    history_cn:"清末币制改革的里程碑。户部壹两为清政府统一币制的首次尝试，因「圆两之争」未果而未正式发行。存世16枚评级，为中国银圆收藏核心标的。",
    history_en:"A milestone in late Qing monetary reform. The Hu Bu One Tael was the first attempt to unify China's currency. Never officially issued due to the Tael vs Dollar debate. 16 graded examples known.",
    auctions:[
      { date:"2024-04", house:"北京诚轩 ChengXuan", lot:"", grade:"PCGS SP63", price_rmb:12075000, price_usd:null, note:"含佣金1207.5万" },
      { date:"2022-08", house:"北京诚轩", lot:"", grade:"PCGS MS63", price_rmb:10000000, price_usd:null, note:"" },
      { date:"2021-04", house:"Stack's Bowers", lot:"", grade:"PCGS SP55", price_rmb:null, price_usd:840000, note:"Pinnacle Collection" },
      { date:"2016", house:"上海拍卖", lot:"", grade:"裸币（后评64+）", price_rmb:2910000, price_usd:null, note:"肖志军购入" },
    ],
    provenance:[
      { holder:"肖志军（深圳）", grade:"MS64+", acquired:"2016", price:"291万（裸币）", status:"持有", note:"评级后价值~2000万" },
      { holder:"陕西李广宏", grade:"", acquired:"", price:"", status:"持有", note:"品相好" },
      { holder:"重庆陶姐", grade:"", acquired:"", price:"", status:"持有", note:"" },
      { holder:"深圳赵勇", grade:"", acquired:"", price:"", status:"持有", note:"" },
      { holder:"王中强（温州）", grade:"MS63", acquired:"", price:"", status:"有出售意向·开价1000万", note:"因女儿购房/移民" },
      { holder:"上海张明", grade:"MS62", acquired:"", price:"", status:"可售", note:"味道好" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"10,000,000+",
  },
  {
    id:"C006", cat:"republic-portrait",
    cn:"民国十六年张作霖像陆海军大元帅纪念壹圆（样币）",
    en:"Chang Tso-lin (Zhang Zuolin) Year 16 Specimen Dollar (1927)",
    era:"民国十六年", year:"1927", mint:"天津造币厂",
    mintEn:"Tientsin Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 9, tier: 1,
    pcgs_pop: { total:5 },
    history_cn:"2025年Heritage以430万美元成交，为近年中国银圆在国际拍卖的最高成交之一。张作霖主政北洋时期天津造币厂试铸，极罕。",
    history_en:"Sold for $4.3M at Heritage December 2025, one of the highest prices for a Chinese coin internationally. Trial strike during Zhang Zuolin's rule of the Beiyang government.",
    auctions:[
      { date:"2025-12-07", house:"Heritage Auctions", lot:"35084", grade:"PCGS SP63", price_rmb:30960000, price_usd:4320000, note:"Heritage HK HKINF Dec 2025, Peh Family Collection Part III" },
      { date:"2023-05", house:"北京诚轩", lot:"", grade:"PCGS SP53", price_rmb:17250000, price_usd:null, note:"2023春拍Top1" },
      { date:"2022", house:"Taisei (Tokyo)", lot:"", grade:"NGC MS62", price_rmb:null, price_usd:2125000, note:"Y17 Mukden Tiger版" },
      { date:"2021-12", house:"Heritage HKINF", lot:"", grade:"NGC认证", price_rmb:null, price_usd:2160000, note:"Y17 Pattern Dollar, NGC世界纪录" },
      { date:"2012-11", house:"Bonhams Hong Kong", lot:"", grade:"SP64+ PCGS", price_rmb:null, price_usd:529000, note:"金币50元版 HKD 410万 (仅2枚)" },
    ],
    provenance:[
      { holder:"陕西李广宏", grade:"", acquired:"", price:"成本2600万", status:"持有", note:"" },
      { holder:"深圳赵勇", grade:"", acquired:"", price:"", status:"持有", note:"" },
      { holder:"重庆陶姐", grade:"AU53", acquired:"", price:"", status:"持有", note:"" },
      { holder:"马太（印尼）", grade:"", acquired:"HA25", price:"", status:"持有Y16版", note:"" },
    ],
    myStatus:"track", myGrade:null, myRank:null,
    est_rmb:"17,000,000+",
  },
  {
    id:"C007", cat:"qing-tael",
    cn:"上海壹两银饼",
    en:"Shanghai One Tael Silver Cake",
    era:"清·咸丰六年", year:"1856", mint:"上海",
    mintEn:"Shanghai",
    metal:"银 Silver", weight:"37.5g", diam:"39mm",
    rarity: 9, tier: 1,
    pcgs_pop: { total:6 },
    history_cn:"中国最早的近代机制银币之一。咸丰六年（1856）上海铸造，为小刀会起义后恢复商贸所需。SBP 2024春拍出现PCGS AU55品。",
    history_en:"One of China's earliest modern milled coins. Struck in Shanghai in 1856 for post-Small Swords Society trade restoration. SBP Spring 2024 featured PCGS AU-55 example.",
    auctions:[
      { date:"2024-04", house:"Stack's Bowers HK", lot:"", grade:"PCGS AU55", price_rmb:null, price_usd:null, note:"Nine Dragons Collection" },
    ],
    provenance:[
      { holder:"李跃明（香港）", grade:"", acquired:"", price:"", status:"持有", note:"石油企业家" },
      { holder:"王中强（温州）", grade:"", acquired:"HS 2022", price:"1260万", status:"有出售意向·开价1500万", note:"" },
      { holder:"江小明", grade:"", acquired:"", price:"", status:"持有一对", note:"2022要价3000-4000万" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"8,000,000+",
  },
  // ─── TIER 2: PREMIUM (3-10M RMB) ───
  {
    id:"C010", cat:"qing-provincial",
    cn:"江南省造光绪元宝七钱二分（喜敦版·光边·无纪年）",
    en:"Kiangnan No-Date 7.2 Mace, Heaton Mint, Smooth Edge (1897)",
    era:"清·光绪", year:"1897", mint:"江南造币厂（喜敦原模）",
    mintEn:"Kiangnan Mint (Heaton original dies)",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 8, tier: 2,
    pcgs_pop: { total:2, ms66:2 },
    history_cn:"喜敦造币厂原模试铸，光边无纪年。1897年英国伯明翰喜敦厂制模运抵江南，首批试铸品。存世仅两枚获MS66高分。本藏品为冠军分之一。",
    history_en:"Heaton Mint original die trial strike, smooth edge, no date mark. Only two examples graded MS66. This piece is co-Champion finest known.",
    auctions:[
      { date:"2025-12-07", house:"Heritage Auctions", lot:"35049", grade:"PCGS SP66", price_rmb:null, price_usd:1500000, note:"Kiangnan SP66 $1.5M (comparable)" },
    ],
    provenance:[
      { holder:"1024 Collection", grade:"MS66", acquired:"", price:"", status:"入藏", note:"冠军分 1/2" },
    ],
    myStatus:"owned", myGrade:"MS66", myRank:"冠军 1/2",
    est_rmb:"10,000,000+",
  },
  {
    id:"C011", cat:"qing-provincial",
    cn:"广东省造光绪元宝七三反版七钱三分",
    en:"Kwangtung 7.3 Mace Reverse Pattern (1889)",
    era:"清·光绪十五年", year:"1889", mint:"广东造币厂",
    mintEn:"Kwangtung Mint",
    metal:"银 Silver", weight:"27.3g", diam:"39mm",
    rarity: 9, tier: 2,
    pcgs_pop: { total:2, ms66p:1, ms67:1 },
    history_cn:"中国机制银圆的「创世纪」。光绪十五年广东造币厂引进喜敦机器后最早试铸。面值七钱三分，背面英文龙图，为「反版」。2025年Heritage以114万美元成交SP67。",
    history_en:"The 'Genesis' of Chinese milled coinage. First trial strikes from Kwangtung Mint after Heaton machinery installation. Heritage Dec 2025 realized $1.14M for SP67.",
    auctions:[
      { date:"2025-12-07", house:"Heritage Auctions", lot:"35057", grade:"PCGS SP67", price_rmb:null, price_usd:1140000, note:"Heritage HK Dec 2025" },
    ],
    provenance:[
      { holder:"1024 Collection", grade:"MS66+", acquired:"", price:"", status:"入藏", note:"亚军 1/2+" },
      { holder:"澳门张安生", grade:"", acquired:"", price:"", status:"持有三套", note:"" },
    ],
    myStatus:"owned", myGrade:"MS66+", myRank:"亚军 1/2+",
    est_rmb:"8,000,000+",
  },
  {
    id:"C012", cat:"republic-sun", pcgs_cert:"48724668",
    cn:"民国十八年孙中山像意大利签字版三帆壹圆（雾面精铸）",
    en:"Year 18 (1929) Sun Yat-sen Italian Signed Junk Dollar, Matte Proof",
    era:"民国十八年", year:"1929", mint:"中央造币厂（上海）",
    mintEn:"Central Mint, Shanghai",
    metal:"银 Silver", weight:"26.7g", diam:"39mm",
    rarity: 9, tier: 2,
    pcgs_pop: { total:2, sp66:2 },
    history_cn:"意大利雕刻师 L. Giorgi 签名版本，雾面精铸工艺。民国十八年中央造币厂委托意大利设计的帆船壹圆试铸品。SP66仅两枚，本藏品为冠军分。",
    history_en:"Signed by Italian engraver L. Giorgi with matte proof finish. Central Mint commissioned Italian-designed Junk Dollar pattern. Only two at SP66; this piece is Champion finest.",
    auctions:[],
    provenance:[
      { holder:"1024 Collection", grade:"SP66", acquired:"", price:"", status:"入藏", note:"冠军 1/2" },
    ],
    myStatus:"owned", myGrade:"SP66", myRank:"冠军 1/2",
    est_rmb:"5,000,000+",
  },
  {
    id:"C013", cat:"republic-yuan",
    cn:"民国五年袁世凯像飞龙冲天冠版壹圆（样币）",
    en:"Yuan Shikai Year 5 (1916) Flying Dragon, Crown Variant Specimen",
    era:"民国五年", year:"1916", mint:"天津造币厂",
    mintEn:"Tientsin Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 8, tier: 2,
    pcgs_pop: { total:10 },
    history_cn:"飞龙系列最珍版别——冲天冠。袁世凯洪宪帝制时期天津造币厂试铸，龙头上冠冲天，极为珍罕。仅10枚获评。",
    history_en:"The rarest variety in the Flying Dragon series — the Crown Variant. Pattern struck during Yuan Shikai's Hong Xian imperial period. Only 10 graded.",
    auctions:[],
    provenance:[
      { holder:"1024 Collection", grade:"SP64", acquired:"", price:"", status:"入藏", note:"亚军 1+1" },
    ],
    myStatus:"owned", myGrade:"SP64", myRank:"亚军 1+1",
    est_rmb:"4,000,000+",
  },
  {
    id:"C014", cat:"republic-yuan", pcgs_cert:"35435978",
    cn:"民国五年袁世凯像飞龙壹圆",
    en:"Yuan Shikai Year 5 (1916) Flying Dragon Dollar",
    era:"民国五年", year:"1916", mint:"天津造币厂",
    mintEn:"Tientsin Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 6, tier: 2,
    pcgs_pop: { total:495, xf40:2, xf45:11, au50:17, au53:20, au55:52, au58:48, ms60:2, ms61:19, ms62:75, ms62p:6, ms63:84, ms63p:13, ms64:72, ms64p:21, ms65:29, ms65p:5, ms66:10, ms66p:5, ms67:3, ms68:1 },
    history_cn:"袁世凯洪宪帝制纪念银圆。正面袁像，背面飞龙图。虽总评级495枚，但MS67仅3枚，MS68唯一。SBP 2024春拍MS66成交。",
    history_en:"Yuan Shikai Hong Xian Empire commemorative. 495 total graded but only 3 at MS67, MS68 unique. The coin is a centerpiece of Republic numismatics.",
    auctions:[
      { date:"2025", house:"Heritage HKINF", lot:"", grade:"PCGS MS66+", price_rmb:null, price_usd:312000, note:"Plumed Hat Dollar" },
      { date:"2024-04", house:"Stack's Bowers HK", lot:"", grade:"PCGS MS62", price_rmb:3920400, price_usd:450000, note:"SBP Apr 2024 Treasures of the Night" },
      { date:"2024-04", house:"Stack's Bowers HK", lot:"", grade:"PCGS MS66", price_rmb:null, price_usd:null, note:"Nine Dragons Collection" },
      { date:"2022-07", house:"Stack's Bowers HK", lot:"", grade:"PCGS MS67", price_rmb:null, price_usd:840000, note:"品种最高价·唯一MS67" },
      { date:"2014-04", house:"Champion HK", lot:"", grade:"NGC MS63", price_rmb:null, price_usd:72000, note:"Hat Touching Rim版" },
    ],
    provenance:[
      { holder:"1024 Collection", grade:"AU58 / MS64 / MS67", acquired:"", price:"", status:"入藏三枚", note:"MS67为亚军分" },
    ],
    myStatus:"owned", myGrade:"MS67", myRank:"亚军",
    est_rmb:"3,000,000+ (MS67)",
  },
  {
    id:"C015", cat:"republic-warlord",
    cn:"黎元洪像无帽版开国纪念壹圆",
    en:"Li Yuanhong Bare Head Opening of Republic Dollar",
    era:"民国", year:"1912", mint:"武昌造币厂",
    mintEn:"Wuchang Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 7, tier: 2,
    pcgs_pop: { total:30, ms65:3 },
    history_cn:"辛亥革命后首批纪念银圆之一。黎元洪为中华民国首任副总统，无帽版为原始设计。MS65仅3枚，本藏品为冠军分。",
    history_en:"Among the first commemorative silver dollars after the 1911 Revolution. Li Yuanhong was ROC's first VP. MS65 is champion grade, only 3 at this level.",
    auctions:[],
    provenance:[
      { holder:"1024 Collection", grade:"MS65", acquired:"", price:"", status:"入藏", note:"冠军 1/3" },
    ],
    myStatus:"owned", myGrade:"MS65", myRank:"冠军 1/3",
    est_rmb:"2,000,000+",
  },
  {
    id:"C016", cat:"republic-warlord",
    cn:"张学良像纪念银币",
    en:"Zhang Xueliang (Young Marshal) Dollar",
    era:"民国", year:"c.1928", mint:"沈阳造币厂",
    mintEn:"Shenyang (Mukden) Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 9, tier: 2,
    pcgs_pop: { total:2, ms61:1, ms63:1 },
    history_cn:"「少帅」张学良纪念币。东北易帜后沈阳造币厂铸造。存世仅2枚获评——MS61与MS63。本藏品MS63为唯一冠军。",
    history_en:"The 'Young Marshal' Zhang Xueliang dollar. Struck at Mukden Mint after the Northeast Flag Replacement. Only 2 graded; this MS63 is the sole champion.",
    auctions:[],
    provenance:[
      { holder:"1024 Collection", grade:"MS63", acquired:"", price:"", status:"入藏", note:"冠军 1·唯一" },
    ],
    myStatus:"owned", myGrade:"MS63", myRank:"冠军 1",
    est_rmb:"3,000,000+",
  },
  {
    id:"C017", cat:"republic-sun",
    pcgs_cert:"50584644",
    cn:"民国十八年孙中山像地球壹圆（镜面精铸）",
    en:"Year 18 (1929) Sun Yat-sen Globe Dollar, Mirror Proof",
    era:"民国十八年", year:"1929", mint:"奥地利维也纳造币厂",
    mintEn:"Vienna Mint, Austria",
    metal:"银 Silver", weight:"26.7g", diam:"39mm",
    rarity: 8, tier: 2,
    pcgs_pop: { total:8, ms61:3, ms62:2, ms63p:2, ms64:1 },
    history_cn:"民国外交银圆杰作。正面孙中山像，背面地球仪象征中国走向世界。镜面精铸工艺，存世仅8枚获评。各大藏家竞相追逐。",
    history_en:"A masterpiece of Republic diplomatic numismatics. Mirror proof finish. Only 8 graded examples, fiercely contested by top collectors.",
    auctions:[],
    provenance:[
      { holder:"重庆陶姐", grade:"MS61", acquired:"", price:"", status:"持有", note:"" },
      { holder:"深圳赵勇", grade:"MS63+", acquired:"", price:"", status:"持有", note:"" },
      { holder:"陕西李广宏", grade:"MS62", acquired:"", price:"从陈吉茂处1200万购入", status:"持有", note:"" },
      { holder:"1024 Collection", grade:"MS61", acquired:"", price:"", status:"入藏", note:"" },
      { holder:"LA陈医生", grade:"MS64?", acquired:"", price:"", status:"持有", note:"估值4000-5000万" },
    ],
    myStatus:"owned", myGrade:"MS61", myRank:null,
    est_rmb:"3,000,000+ (MS61)",
  },
  {
    id:"C018", cat:"qing-provincial",
    cn:"湖北省造光绪元宝本省七钱二分",
    en:"Hupeh 'Ben Sheng' (Provincial) Dollar",
    era:"清·光绪", year:"c.1894", mint:"湖北造币厂",
    mintEn:"Hupeh Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 9, tier: 1,
    pcgs_pop: { total:2, au53:1, ms64:1 },
    history_cn:"湖北省造「本省」银圆，面额直书「本省」二字，表明仅在湖北省内流通。存世极罕，评级仅2枚。MS64为深圳赵勇2016年以800万从CC处购入。",
    history_en:"The Hupeh 'Ben Sheng' dollar, inscribed for provincial-only circulation. Only 2 graded. MS64 acquired by Zhao Yong in 2016 for 8M from CC.",
    auctions:[],
    provenance:[
      { holder:"深圳赵勇", grade:"MS64", acquired:"2016", price:"800万（CC处）", status:"持有", note:"只买不卖" },
      { holder:"澳门张安生", grade:"MS64?", acquired:"", price:"", status:"持有", note:"" },
      { holder:"老姚", grade:"AU53", acquired:"", price:"", status:"海关没收品", note:"白家旧藏" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"8,000,000+",
  },
  {
    id:"C019", cat:"republic-sun",
    cn:"民国二十一年孙中山像金本位壹圆（下三鸟）",
    en:"Year 21 (1932) Sun Yat-sen Gold Standard Dollar (Birds Below Sun)",
    era:"民国二十一年", year:"1932", mint:"中央造币厂（上海）",
    mintEn:"Central Mint, Shanghai",
    metal:"银 Silver", weight:"26.7g", diam:"39mm",
    rarity: 9, tier: 1,
    pcgs_pop: { total:2, ms60:1, ms61:1 },
    history_cn:"金本位币制改革纪念币。三鸟在日下方（「下三鸟」），与普通版三鸟在日上方不同。存世仅2枚评级，为中国银圆最珍稀品种之一。",
    history_en:"Gold Standard monetary reform commemorative. Birds below the sun (vs above in regular issue). Only 2 graded, among the rarest Chinese silver dollars.",
    auctions:[
      { date:"2025-05", house:"SBP Hong Kong", lot:"", grade:"NGC MS", price_rmb:null, price_usd:null, note:"2025春Top1 金本位领衔" },
      { date:"2024-04-15", house:"Stack's Bowers", lot:"40212", grade:"NGC MS62", price_rmb:null, price_usd:528000, note:"Rarities Night" },
      { date:"2012", house:"SBP", lot:"", grade:"", price_rmb:null, price_usd:113000, note:"铜质off-metal" },
    ],
    provenance:[
      { holder:"重庆陶姐", grade:"MS63?", acquired:"", price:"", status:"持有", note:"" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"10,000,000+",
  },
  {
    id:"C020", cat:"republic-yuan",
    cn:"民国三年袁世凯像壹圆签字版",
    en:"Yuan Shikai Year 3 (1914) Signed Dollar (L. Giorgi)",
    era:"民国三年", year:"1914", mint:"天津造币厂",
    mintEn:"Tientsin Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 8, tier: 2,
    pcgs_pop: { total:12 },
    history_cn:"意大利雕刻师 L. Giorgi 签名试铸版。正面袁世凯像，六点钟方向刻有「L.GIORGI」签名。民国人像银圆的标志性品种。",
    history_en:"L. Giorgi signed pattern strike. The Italian engraver's signature appears at 6 o'clock. An iconic Republic portrait coin.",
    auctions:[
      { date:"2024-12", house:"Heritage Hong Kong", lot:"", grade:"NGC MS64", price_rmb:null, price_usd:null, note:"Nine Dragons Collection" },
      { date:"2021", house:"国内拍卖", lot:"", grade:"", price_rmb:6000000, price_usd:null, note:"评级品成交" },
      { date:"2019", house:"中国嘉德", lot:"", grade:"", price_rmb:2760000, price_usd:null, note:"春拍" },
    ],
    provenance:[
      { holder:"李跃明（香港）", grade:"MS64", acquired:"", price:"", status:"持有", note:"" },
      { holder:"王中强（温州）", grade:"MS63", acquired:"", price:"", status:"有出售意向", note:"弱打" },
    ],
    myStatus:"want", myGrade:null, myRank:null,
    est_rmb:"5,000,000+",
  },
  // ─── ADDITIONAL OWNED PIECES ───
  {
    id:"C030", cat:"qing-dragon", pcgs_cert:"35378884",
    cn:"宣统三年大清银币壹圆（反龙版）",
    en:"Hsuan Tung Year 3 Reverse Dragon Dollar (1911)",
    era:"清·宣统三年", year:"1911", mint:"天津造币总厂",
    mintEn:"Tientsin Central Mint",
    metal:"银 Silver", weight:"26.9g", diam:"39mm",
    rarity: 6, tier: 3,
    pcgs_pop: { total:57 },
    history_cn:"宣三反龙为大清银币流通版本中的珍品。反龙图设计龙身反转，区别于正龙版。评级57枚，MS62+至MS66均有分布。",
    history_en:"The Reverse Dragon is a prized circulation variety. 57 graded, distributed from MS62+ through MS66.",
    auctions:[
      { date:"2023-04-17", house:"Stack's Bowers", lot:"40162", grade:"PCGS SP65", price_rmb:null, price_usd:1380000, note:"Type II反龙" },
    ],
    provenance:[
      { holder:"1024 Collection", grade:"MS62+", acquired:"", price:"", status:"入藏", note:"" },
    ],
    myStatus:"owned", myGrade:"MS62+", myRank:null,
    est_rmb:"500,000+",
  },
  {
    id:"C031", cat:"qing-tael",
    cn:"北洋造光绪元宝库平壹两（三点版）",
    en:"Pei Yang Arsenal One Tael, 3-Dot Variant",
    era:"清·光绪三十三年", year:"1907", mint:"北洋机器局",
    mintEn:"Pei Yang Arsenal",
    metal:"银 Silver", weight:"37.3g", diam:"39mm",
    rarity: 8, tier: 2,
    pcgs_pop: { total:8, au55:1, au58:1, ms61:3, ms62:2, ms63:1, ms63p:1 },
    history_cn:"北洋壹两为继户部壹两后第二种「两」面额银圆。三点版为版别特征。2023年诚轩以690万成交。评级仅8枚。",
    history_en:"The Beiyang One Tael is the second 'Tael' denomination after Hu Bu. 3-dot variant. ChengXuan 2023 realized 6.9M RMB. Only 8 graded.",
    auctions:[
      { date:"2023-05", house:"北京诚轩", lot:"", grade:"", price_rmb:6900000, price_usd:null, note:"光绪33年北洋一两三点版" },
    ],
    provenance:[
      { holder:"1024 Collection", grade:"MS62", acquired:"", price:"", status:"入藏", note:"季军分" },
      { holder:"王中强（温州）", grade:"MS62", acquired:"", price:"", status:"开价1380万", note:"HS 61品22年2070万" },
    ],
    myStatus:"owned", myGrade:"MS62", myRank:"季军",
    est_rmb:"6,000,000+",
  },
  {
    id:"C032", cat:"qing-tael",
    cn:"大清户部造币总厂丙午中字壹两",
    en:"Board of Revenue Bingwu Zhongzi One Tael (1906)",
    era:"清·光绪丙午年", year:"1906", mint:"天津户部造币总厂",
    mintEn:"Board of Revenue Mint, Tientsin",
    metal:"银 Silver", weight:"37.3g", diam:"39mm",
    rarity: 7, tier: 2,
    pcgs_pop: { total:8, ms65:4, ms65p:1, ms66:1 },
    history_cn:"丙午中字壹两，面值中间有「中」字。光绪丙午年造币总厂试铸。评级8枚，MS65四枚并列季军。",
    history_en:"The Bingwu 'Zhongzi' One Tael, with the character 'Zhong' (middle) in the center. 8 graded, four at MS65 in tie for 3rd place.",
    auctions:[
      { date:"2025-12-07", house:"Heritage Auctions", lot:"35027", grade:"PCGS SP64+", price_rmb:null, price_usd:1260000, note:"Kuping Tael Gold $1.26M (gold版)" },
    ],
    provenance:[
      { holder:"1024 Collection", grade:"MS65", acquired:"", price:"", status:"入藏", note:"季军分" },
      { holder:"肖志军（深圳）", grade:"MS65+", acquired:"", price:"要价5000万", note:"", status:"持有" },
      { holder:"王中强（温州）", grade:"MS65", acquired:"", price:"开价600万", status:"有出售意向", note:"" },
    ],
    myStatus:"owned", myGrade:"MS65", myRank:"季军",
    est_rmb:"5,000,000+",
  },
  {
    id:"C033", cat:"qing-provincial",
    cn:"湖北省造双龙一两大字版",
    en:"Hupeh Double Dragon One Tael, Large Character",
    era:"清·光绪", year:"c.1902", mint:"湖北造币厂",
    mintEn:"Hupeh Mint",
    metal:"银 Silver", weight:"37.3g", diam:"39mm",
    rarity: 7, tier: 3,
    pcgs_pop: { total:32 },
    history_cn:"湖北双龙壹两为清末湖北造币厂铸造。大字版与小字版以面文字体大小区分。评级32枚。",
    history_en:"Hupeh Double Dragon One Tael. Large Character variant distinguished by larger face text. 32 graded.",
    auctions:[],
    provenance:[
      { holder:"1024 Collection", grade:"XF40 / MS63", acquired:"", price:"", status:"入藏两枚", note:"" },
    ],
    myStatus:"owned", myGrade:"XF40/MS63", myRank:null,
    est_rmb:"1,000,000+",
  },
  {
    id:"C034", cat:"qing-provincial",
    cn:"湖北省造双龙一两小字版",
    en:"Hupeh Double Dragon One Tael, Small Character",
    era:"清·光绪", year:"c.1902", mint:"湖北造币厂",
    mintEn:"Hupeh Mint",
    metal:"银 Silver", weight:"37.3g", diam:"39mm",
    rarity: 5, tier: 3,
    pcgs_pop: { total:286 },
    history_cn:"小字版存量相对较大，评级286枚。但高分仍珍——MS64以上仅27枚，MS65仅2枚。",
    history_en:"The Small Character variant has larger population (286 graded) but high grades remain scarce — only 27 above MS64, just 2 at MS65.",
    auctions:[],
    provenance:[
      { holder:"1024 Collection", grade:"AU53/MS61/MS62+/MS64", acquired:"", price:"", status:"入藏四枚", note:"" },
      { holder:"kent（杭州）", grade:"", acquired:"", price:"600-1900万不等", status:"持有大量", note:"和强关系好" },
    ],
    myStatus:"owned", myGrade:"MS64", myRank:null,
    est_rmb:"800,000+ (MS64)",
  },
  // ─── MORE OWNED PIECES (COMPACT) ───
  { id:"C035", cat:"republic-warlord", pcgs_cert:"86294947", cn:"张作霖像纪念章", en:"Zhang Zuolin Commemorative Medal", era:"民国", year:"c.1927", mint:"天津", mintEn:"Tientsin", metal:"银", weight:"26g", diam:"38mm", rarity:7, tier:3, pcgs_pop:{total:3}, history_cn:"张作霖大元帅像纪念章，天津造币厂铸造。与张作霖壹圆同期制作，但非流通货币，而是赠送军政要员的礼品章。存世仅3枚获评，极为珍罕。因非标准货币，评级多为Detail级别，但其历史价值远超品相。", history_en:"Zhang Zuolin Marshal commemorative medal, struck at Tientsin alongside the regular dollar. Not circulation currency but a gift medal for military-political dignitaries. Only 3 graded examples known.", auctions:[{date:"2023-08",house:"上海泓盛",lot:"",grade:"NGC AU Detail",price_rmb:null,price_usd:null,note:"同品种参考"}], provenance:[{holder:"1024 Collection",grade:"AU Detail",acquired:"",price:"",status:"入藏",note:"3枚之一"}], myStatus:"owned", myGrade:"AU Detail", myRank:null, est_rmb:"1,000,000+" },
  { id:"C036", cat:"republic-warlord", cn:"黎元洪像戴帽版开国纪念壹圆", en:"Li Yuanhong With Hat Dollar", era:"民国", year:"1912", mint:"武昌造币厂", mintEn:"Wuchang Mint", metal:"银 Silver", weight:"26.9g", diam:"39mm", rarity:6, tier:3, pcgs_pop:{total:50,ms62:8,ms63:12,ms64:6,ms65:2}, history_cn:"辛亥革命后武昌造币厂铸造的首批纪念银圆。戴帽版黎元洪头戴军帽，表现其军人身份，较无帽版更为常见。但MS64以上仅8枚，高分仍极珍贵。与无帽版共同构成民国开国纪念银圆的双子星。", history_en:"First commemorative dollars from Wuchang Mint after the 1911 Revolution. The hatted variant shows Li Yuanhong in military cap, more common than bare head but only 8 above MS64 — high grades remain very scarce.", auctions:[{date:"2024-06",house:"北京诚轩",lot:"",grade:"PCGS MS64",price_rmb:690000,price_usd:null,note:"2024春"}], provenance:[{holder:"1024 Collection",grade:"MS62 / MS64",acquired:"",price:"",status:"入藏两枚",note:"MS64品相极佳"}], myStatus:"owned", myGrade:"MS62/MS64", myRank:null, est_rmb:"500,000+" },
  { id:"C037", cat:"republic-yuan", pcgs_cert:"85826877", cn:"袁世凯像共和纪念壹圆签字版（镜面精铸）", en:"Yuan Gonghe Signed Dollar, Mirror Proof", era:"民国三年", year:"1914", mint:"天津造币厂", mintEn:"Tientsin Mint", metal:"银 Silver", weight:"26.9g", diam:"39mm", rarity:8, tier:2, pcgs_pop:{total:5,ms63:2,ms63p:1,ms64:1,sp65:1}, history_cn:"袁世凯共和纪念壹圆签字版，意大利雕刻师 L. Giorgi 签名。镜面精铸工艺——币面呈现镜面光泽，区别于普通流通币的缎面光泽。此版为天津造币厂最高规格的试铸品之一，仅5枚获评。签字位于六点钟方向，刻有「L.GIORGI」。", history_en:"Yuan Shikai Gonghe (Republic) signed dollar with L. Giorgi signature. Mirror proof finish — the coin surface displays mirror-like luster. One of Tientsin Mint's highest-spec pattern strikes. Only 5 graded. Signature at 6 o'clock reads 'L.GIORGI'.", auctions:[{date:"2022-05",house:"Stack's Bowers",lot:"",grade:"PCGS SP65",price_rmb:null,price_usd:960000,note:"共和签字SP65"},{date:"2023-12",house:"北京诚轩",lot:"",grade:"PCGS MS63+",price_rmb:4600000,price_usd:null,note:"镜面精铸"}], provenance:[{holder:"1024 Collection",grade:"MS63+",acquired:"",price:"",status:"入藏",note:"镜面精铸"}], myStatus:"owned", myGrade:"MS63+", myRank:null, est_rmb:"2,000,000+" },
  { id:"C038", cat:"republic-yuan", cn:"袁世凯像共和纪念壹圆", en:"Yuan Gonghe Commemorative Dollar", era:"民国三年", year:"1914", mint:"天津造币厂", mintEn:"Tientsin Mint", metal:"银 Silver", weight:"26.9g", diam:"39mm", rarity:5, tier:3, pcgs_pop:{total:925,ms60:42,ms61:88,ms62:210,ms63:190,ms64:112,ms65:28,ms66:3}, history_cn:"民国三年袁世凯像共和纪念壹圆，纪念中华民国共和体制确立。正面袁像，背面嘉禾纹，上方「中华民国共和纪念币」。虽总评级925枚，但MS66仅3枚，高分仍是收藏的制高点。", history_en:"Year 3 Yuan Shikai Gonghe (Republic) commemorative dollar. Celebrates the establishment of the Republican system. 925 total graded but only 3 at MS66.", auctions:[{date:"2024-04",house:"SBP",lot:"",grade:"PCGS MS63",price_rmb:null,price_usd:36000,note:"标准版"}], provenance:[{holder:"1024 Collection",grade:"MS61 / MS62",acquired:"",price:"",status:"入藏两枚",note:""}], myStatus:"owned", myGrade:"MS62", myRank:null, est_rmb:"300,000+" },
  { id:"C039", cat:"republic-sun", pcgs_cert:"50584643", cn:"孙中山像开国纪念壹角", en:"Sun Yat-sen Memento 10 Cents (1912)", era:"民国元年", year:"1912", mint:"南京造币厂", mintEn:"Nanking Mint", metal:"银 Silver", weight:"2.7g", diam:"18mm", rarity:7, tier:3, pcgs_pop:{total:9,ms60:1,ms61:2,ms62:3,ms63:2,ms64:1}, history_cn:"中华民国开国纪念壹角银币。民国元年南京造币厂铸造。正面孙中山侧面像，背面嘉禾纹环绕「壹角」面额。存世极罕，评级仅9枚。MS63为本品等级，位居前列。辛亥革命后最早的小面额纪念银币之一。", history_en:"Republic of China Memento 10 cents. Struck at Nanking Mint in 1912. Sun Yat-sen profile on obverse. Only 9 graded. MS63 ranks among the finest. One of the earliest small-denomination commemorative silver coins after the 1911 Revolution.", auctions:[{date:"2021-12",house:"SBP Hong Kong",lot:"",grade:"PCGS MS62",price_rmb:null,price_usd:72000,note:""}], provenance:[{holder:"1024 Collection",grade:"MS63",acquired:"",price:"",status:"入藏",note:""}], myStatus:"owned", myGrade:"MS63", myRank:null, est_rmb:"200,000+" },
  { id:"C040", cat:"republic-sun", cn:"民国二十一年孙中山像三鸟壹圆（上三鸟）", en:"Year 21 Sun San Niao (Birds Above) Dollar", era:"民国二十一年", year:"1932", mint:"上海", mintEn:"Shanghai Central Mint", metal:"银", weight:"26.7g", diam:"39mm", rarity:4, tier:3, pcgs_pop:{total:1949}, history_cn:"上三鸟为民国大宗品种，总评级1949枚。MS64为本藏品等级。", history_en:"Major Republic type, 1949 total graded.", auctions:[], provenance:[{holder:"1024 Collection",grade:"MS64",acquired:"",price:"",status:"入藏",note:""}], myStatus:"owned", myGrade:"MS64", myRank:null, est_rmb:"200,000+" },
  { id:"C041", cat:"republic-sun", cn:"民国二十一年孙中山像三鸟壹圆铜质样币", en:"Year 21 Sun San Niao Copper Pattern", era:"民国二十一年", year:"1932", mint:"上海中央造币厂", mintEn:"Shanghai Central Mint", metal:"铜 Copper", weight:"26g", diam:"39mm", rarity:9, tier:2, pcgs_pop:{total:2,sp62:1,sp63:1}, history_cn:"三鸟壹圆铜质试铸样币。中央造币厂在正式银币投产前，以铜坯料试铸以检验模具。此铜质样币存世仅2枚获评，为三鸟系列中最珍贵的版别之一。铜面呈现红棕色原始包浆，边缘锐利。", history_en:"San Niao (Three Birds) copper trial strike pattern. The Central Mint used copper blanks for die testing before silver production. Only 2 graded — among the rarest in the San Niao series. Original reddish-brown patina with sharp edges.", auctions:[{date:"2019-04",house:"SBP Hong Kong",lot:"",grade:"PCGS SP62",price_rmb:null,price_usd:480000,note:"铜样"}], provenance:[{holder:"1024 Collection",grade:"SP",acquired:"",price:"",status:"入藏",note:"2枚之一"}], myStatus:"owned", myGrade:"SP", myRank:null, est_rmb:"1,000,000+" },
  { id:"C042", cat:"republic-sun", cn:"民国二十二年孙中山像帆船壹圆铜质样币", en:"Year 22 Sun Junk Dollar Copper Pattern", era:"民国二十二年", year:"1933", mint:"上海中央造币厂", mintEn:"Shanghai Central Mint", metal:"铜 Copper", weight:"26g", diam:"39mm", rarity:9, tier:2, pcgs_pop:{total:2,sp63:1,sp64:1}, history_cn:"帆船壹圆铜质试铸样币。民国二十二年中央造币厂以铜坯料试铸帆船壹圆。背面帆船图案清晰锐利，显示模具的极佳状态。铜质样币较银质正式发行品更为罕见，存世仅2枚获评。此为研究民国币制改革的重要实物。", history_en:"Junk Dollar copper trial strike pattern. Year 22 Central Mint copper blank test. Reverse junk design is sharp and crisp, showing excellent die condition. Rarer than the silver issue — only 2 graded. Important material evidence of Republic monetary reform.", auctions:[{date:"2020-10",house:"Heritage Hong Kong",lot:"",grade:"PCGS SP63",price_rmb:null,price_usd:360000,note:"铜样帆船"}], provenance:[{holder:"1024 Collection",grade:"SP",acquired:"",price:"",status:"入藏",note:"2枚之一"}], myStatus:"owned", myGrade:"SP", myRank:null, est_rmb:"1,000,000+" },
  { id:"C043", cat:"republic-sun", cn:"民国二十四年孙中山像帆船中圆", en:"Year 24 Sun Junk Half Dollar", era:"民国二十四年", year:"1935", mint:"上海", mintEn:"Shanghai", metal:"银", weight:"13.4g", diam:"33mm", rarity:8, tier:2, pcgs_pop:{total:2}, history_cn:"帆船中圆，评级仅2枚。", history_en:"Junk half dollar, only 2 graded.", auctions:[], provenance:[{holder:"1024 Collection",grade:"MS62",acquired:"",price:"",status:"入藏",note:"冠军 1"}], myStatus:"owned", myGrade:"MS62", myRank:"冠军 1", est_rmb:"3,000,000+" },
  { id:"C044", cat:"qing-provincial", cn:"广东省造光绪元宝七三反版七分三厘", en:"Kwangtung 7.3 Candareens Reverse Pattern (1889)", era:"清·光绪十五年", year:"1889", mint:"广东造币厂", mintEn:"Kwangtung Mint", metal:"银 Silver", weight:"2.7g", diam:"18mm", rarity:9, tier:2, pcgs_pop:{total:3}, history_cn:"七三反版小面额七分三厘，与七钱三分同为广东造币厂最早试铸。小面额存世更罕，评级仅3枚。中国机制银圆「创世纪」的辅币见证。", history_en:"The small denomination 7.3 Candareens reverse pattern, struck alongside the 7.3 Mace. Even rarer than the large denomination — only 3 graded.", auctions:[], provenance:[{holder:"1024 Collection",grade:"SP",acquired:"",price:"",status:"入藏",note:""}], myStatus:"owned", myGrade:"SP", myRank:null, est_rmb:"2,000,000+" },
  { id:"C045", cat:"qing-tael", cn:"大清户部造币总厂丙午中字壹钱", en:"Kuping Chung-Tze One Mace (1906)", era:"清·光绪丙午年", year:"1906", mint:"天津户部造币总厂", mintEn:"Tientsin Central Mint", metal:"银 Silver", weight:"3.73g", diam:"20mm", rarity:8, tier:2, pcgs_pop:{total:5}, history_cn:"中字壹钱为「两」制体系最小面额试铸品之一。与中字壹两同为光绪丙午年户部造币总厂铸造，面值中间有「中」字。评级仅5枚，极为珍罕。", history_en:"The smallest denomination in the 'Tael' system trial series. Struck at Tientsin alongside the Chung-Tze Tael. Only 5 graded.", auctions:[], provenance:[{holder:"1024 Collection",grade:"SP",acquired:"",price:"",status:"入藏",note:""}], myStatus:"owned", myGrade:"SP", myRank:null, est_rmb:"1,500,000+" },
  { id:"C046", cat:"republic-yuan", cn:"民国五年袁世凯像飞龙签字版壹圆", en:"Yuan Shikai Year 5 (1916) Flying Dragon Signed Dollar (L. Giorgi)", era:"民国五年", year:"1916", mint:"天津造币厂", mintEn:"Tientsin Mint", metal:"银 Silver", weight:"26.9g", diam:"39mm", rarity:9, tier:2, pcgs_pop:{total:8}, history_cn:"飞龙签字版，意大利雕刻师 L. Giorgi 签名于六点钟方向。天津造币厂为洪宪帝制铸造的最高规格试铸品之一。签字版较普通飞龙更为珍罕，评级仅8枚。与冲天冠版共同构成飞龙系列的顶级珍品。", history_en:"Flying Dragon signed dollar with L. Giorgi signature at 6 o'clock. One of the highest-spec pattern strikes from Tientsin for the Hong Xian Empire. Only 8 graded.", auctions:[{date:"2023-08",house:"SBP Hong Kong",lot:"",grade:"PCGS SP63",price_rmb:null,price_usd:720000,note:"飞龙签字SP63"}], provenance:[{holder:"1024 Collection",grade:"SP",acquired:"",price:"",status:"入藏",note:""}], myStatus:"owned", myGrade:"SP", myRank:null, est_rmb:"3,000,000+" },
];

// ===== MAJOR AUCTION RECORDS DATABASE =====
const AUCTION_RECORDS = [
  // INTERNATIONAL RECORDS (USD)
  { date:"2025-12-07", house:"Heritage", loc:"Hong Kong", cn:"张作霖十六年像壹圆 SP63", en:"Zhang Zuolin Y16 SP63", grade:"PCGS SP63", lot:"35084", usd:4300000, rmb:30960000 },
  { date:"2025-12-07", house:"Heritage", loc:"Hong Kong", cn:"江南省造喜敦版七钱二分 SP66", en:"Kiangnan Heaton SP66", grade:"PCGS SP66", lot:"35049", usd:1500000, rmb:10800000 },
  { date:"2025-12-07", house:"Heritage", loc:"Hong Kong", cn:"广东七三反版 SP67", en:"Kwangtung 7.3 Rev SP67", grade:"PCGS SP67", lot:"35057", usd:1140000, rmb:8208000 },
  { date:"2025-12-07", house:"Heritage", loc:"Hong Kong", cn:"丙午壹两金币 SP64+", en:"Kuping Tael Gold SP64+", grade:"PCGS SP64+", lot:"35027", usd:1260000, rmb:9072000 },
  { date:"2025-06-18", house:"Heritage", loc:"Hong Kong", cn:"丙午壹两银币后铸 SP66", en:"Kuping Tael Restrike SP66", grade:"PCGS SP66", lot:"34010", usd:810000, rmb:5832000 },
  { date:"2024-10-15", house:"SBP", loc:"Hong Kong", cn:"新疆饷银壹两样币 SP40", en:"Sinkiang Sungarei Tael SP40", grade:"PCGS SP40", lot:"41211", usd:360000, rmb:2592000 },
  { date:"2024-04", house:"SBP", loc:"Hong Kong", cn:"袁像飞龙壹圆 MS62", en:"Yuan Flying Dragon MS62", grade:"PCGS MS62", lot:"", usd:450000, rmb:3920400 },
  { date:"2023-04-17", house:"SBP", loc:"Hong Kong", cn:"宣三反龙 Type II SP65", en:"Xuan3 Rev Dragon SP65", grade:"PCGS SP65", lot:"40162", usd:1380000, rmb:9936000 },
  { date:"2022-05-04", house:"SBP", loc:"Hong Kong", cn:"宣三长须龙 SP63+", en:"Long Whisker Dragon SP63+", grade:"PCGS SP63+", lot:"51134", usd:3000000, rmb:21000000 },
  { date:"2022-05-04", house:"SBP", loc:"Hong Kong", cn:"江南喜敦版半元 MS62+ PL", en:"Kiangnan Prowing MS62+PL", grade:"PCGS MS62+PL", lot:"51040", usd:1200000, rmb:8640000 },
  { date:"2022-04-29", house:"Taisei/Royal Mint", loc:"Tokyo", cn:"1867香港壹两样币 PF63+", en:"HK Pattern Tael PF63+", grade:"NGC PF63+", lot:"218", usd:1990000, rmb:null },
  { date:"2021-12", house:"Heritage", loc:"Hong Kong", cn:"张作霖十六年壹圆 SP62", en:"Zhang Zuolin Y16 SP62", grade:"NGC SP62", lot:"", usd:2160000, rmb:15552000 },
  { date:"2021-12-02", house:"SBP", loc:"Hong Kong", cn:"大清丙午壹两银币后铸 SP65", en:"Kuping Tael Restrike SP65", grade:"PCGS SP65", lot:"42054", usd:1350000, rmb:9720000 },
  { date:"2021-12-02", house:"SBP", loc:"Hong Kong", cn:"宣统大清七钱二分 SP64+", en:"Tai-Ching-Ti-Kuo SP64+", grade:"PCGS SP64+", lot:"42043", usd:1260000, rmb:9072000 },
  { date:"2021-12-02", house:"SBP", loc:"Hong Kong", cn:"北洋三十四年 SP64", en:"Chihli Pei Yang Y34 SP64", grade:"PCGS SP64", lot:"42044", usd:960000, rmb:6912000 },
  { date:"2021-10", house:"SBP", loc:"Hong Kong", cn:"陕西省造三钱六分样币 SP63", en:"Shen-Si Province Pattern SP63", grade:"PCGS SP63", lot:"23062", usd:600000, rmb:4320000 },
  { date:"2021-04-06", house:"SBP", loc:"Hong Kong", cn:"大清丙午壹两银币样币 SP55", en:"Kuping Tael Pattern SP55", grade:"PCGS SP55", lot:"50006", usd:840000, rmb:6048000 },
  { date:"2021-04-06", house:"SBP", loc:"Hong Kong", cn:"大清丁未七钱二分 MS65+", en:"Tai-Ching 1907 Pattern MS65+", grade:"PCGS MS65+", lot:"50008", usd:500000, rmb:3600000 },
  { date:"2018-06-28", house:"Heritage", loc:"Hong Kong", cn:"浙江省造七钱二分 MS66", en:"Chekiang Dragon Dollar MS66", grade:"NGC MS66", lot:"30074", usd:440000, rmb:3168000 },
  { date:"2018-06-28", house:"Heritage", loc:"Hong Kong", cn:"江南己亥半元 MS62 PL", en:"Kiangnan 1899 Half MS62PL", grade:"NGC MS62PL", lot:"30088", usd:310000, rmb:2232000 },
  // CHINESE DOMESTIC RECORDS (RMB)
  { date:"2022-08-12", house:"北京诚轩", loc:"北京", cn:"奉天癸卯壹两 SP63", en:"Fengtian Guimao Tael SP63", grade:"PCGS SP63", lot:"2562", usd:6900000, rmb:46575000 },
  { date:"2022-08", house:"北京诚轩", loc:"北京", cn:"张作霖十六年伍拾圆金币", en:"Zhang Zuolin Y16 Gold 50 Yuan", grade:"", lot:"", usd:null, rmb:34500000 },
  { date:"2024-04", house:"北京诚轩", loc:"北京", cn:"户部壹两 SP63", en:"Hu Bu One Tael SP63", grade:"PCGS SP63", lot:"", usd:null, rmb:12075000 },
  { date:"2023-05", house:"北京诚轩", loc:"北京", cn:"张作霖十五年壹圆 SP53", en:"Zhang Zuolin Y15 SP53", grade:"PCGS SP53", lot:"", usd:null, rmb:17250000 },
  { date:"2023-05", house:"北京诚轩", loc:"北京", cn:"北洋壹两三点版", en:"Beiyang One Tael 3-dot", grade:"", lot:"", usd:null, rmb:6900000 },
  // NEW — from research agent
  { date:"2025-06-20", house:"Heritage", loc:"Hong Kong", cn:"宣三长须龙 SP63 (后铸)", en:"Long Whisker Restrike SP63", grade:"NGC SP63", lot:"", usd:504000, rmb:null },
  { date:"2025-06-20", house:"Heritage", loc:"Hong Kong", cn:"宣三长须龙 SP63+ (后铸)", en:"Long Whisker Restrike SP63+", grade:"NGC SP63+", lot:"", usd:408000, rmb:null },
  { date:"2024-06", house:"Heritage", loc:"Hong Kong", cn:"宣三长须龙 SP63", en:"Long Whisker Dragon SP63", grade:"NGC SP63", lot:"", usd:690000, rmb:null },
  { date:"2024-04-15", house:"SBP", loc:"Hong Kong", cn:"金本位下三鸟 MS62", en:"Birds Under Junk MS62", grade:"NGC MS62", lot:"40212", usd:528000, rmb:null },
  { date:"2022-07", house:"SBP", loc:"Hong Kong", cn:"飞龙壹圆 MS67", en:"Flying Dragon MS67", grade:"PCGS MS67", lot:"", usd:840000, rmb:null },
  { date:"2022", house:"Taisei", loc:"Tokyo", cn:"张作霖Y17 MS62", en:"Zhang Zuolin Y17 MS62", grade:"NGC MS62", lot:"", usd:2125000, rmb:null },
  { date:"2021-11", house:"北京诚轩", loc:"北京", cn:"宣三长须龙 SP62", en:"Long Whisker SP62", grade:"PCGS SP62", lot:"", usd:null, rmb:6727500 },
  { date:"2021-05", house:"北京诚轩", loc:"北京", cn:"宣三长须龙 SP63", en:"Long Whisker SP63", grade:"PCGS SP63", lot:"", usd:null, rmb:5750000 },
  { date:"2021-05", house:"北京诚轩", loc:"北京", cn:"宣三短须龙 SP63", en:"Short Whisker SP63", grade:"PCGS SP63", lot:"", usd:null, rmb:5750000 },
  { date:"2021-04", house:"SBP", loc:"Hong Kong", cn:"宣三长须龙 SP64 (Pinnacle)", en:"Long Whisker SP64 Pinnacle", grade:"PCGS SP64", lot:"", usd:1020000, rmb:null },
  { date:"2021-04-06", house:"SBP", loc:"Hong Kong", cn:"户部壹两 SP55 (Pinnacle)", en:"Hu Bu Tael SP55 Pinnacle", grade:"PCGS SP55", lot:"50006", usd:840000, rmb:null },
  { date:"2021", house:"国内拍卖", loc:"北京", cn:"袁大头签字版", en:"Yuan Signed Dollar", grade:"", lot:"", usd:null, rmb:6000000 },
  { date:"2019-06", house:"Heritage", loc:"Hong Kong", cn:"七三反版 MS64+", en:"73 Reverse MS64+", grade:"NGC MS64+", lot:"", usd:228000, rmb:null },
  { date:"2019", house:"中国嘉德", loc:"北京", cn:"袁大头签字版", en:"Yuan Signed Dollar", grade:"", lot:"", usd:null, rmb:2760000 },
  { date:"2012-11", house:"Bonhams", loc:"Hong Kong", cn:"张作霖金币50元 SP64+", en:"Zhang Zuolin Gold 50Y SP64+", grade:"PCGS SP64+", lot:"", usd:529000, rmb:null },
];

// ===== COLLECTORS DEEP ANALYSIS =====
const COLLECTORS = [
  {
    id:"COL01", cn:"肖志军", en:"Xiao Zhijun",
    loc_cn:"深圳", loc_en:"Shenzhen", age:"57",
    bg_cn:"最高分大藏家，拥有评级公司，投资英伟达。30年专业藏家，追求品质但价格合理。",
    bg_en:"Top-grade mega-collector, owns grading company, NVDA investor. 30-year veteran, quality-driven.",
    wealth:"A", mode:"hold", will_cn:"低", will_en:"Low",
    coins:[
      { coin_id:"C005", cn:"户部壹两", grade:"MS64+", cost:"291万（裸币）", current_est:"2000万", acquired:"2016 上海拍卖" },
      { coin_id:"C031", cn:"北洋壹两", grade:"裸币", cost:"690万", current_est:"1000万+", acquired:"" },
      { coin_id:"C032", cn:"中字壹两", grade:"MS65+", cost:"", current_est:"5000万（要价）", acquired:"" },
    ],
    network:["kent", "王中强"],
    analysis_cn:"肖是深圳最资深的银圆藏家之一，拥有自己的评级公司。其户部壹两以291万裸币价购入后评级MS64+，增值近7倍。中字壹两MS65+要价5000万，说明其对顶级品的定价极为自信。10年后财力将更强。",
    analysis_en:"Xiao is one of Shenzhen's most senior collectors with his own grading company. His Hu Bu Tael, bought raw for 2.91M, graded MS64+ — a ~7x appreciation. His 50M ask for the Zhongzi Tael MS65+ shows extreme confidence in top-tier pricing.",
  },
  {
    id:"COL02", cn:"李广宏", en:"Li Guanghong",
    loc_cn:"陕西宝鸡", loc_en:"Shaanxi Baoji", age:"50",
    bg_cn:"地产商，赵洋洋/赵村长介绍入圈。喜欢黄金和金币，陈吉茂粉丝。不买毫子。",
    bg_en:"Real estate mogul, introduced by Zhao Yangyang. Loves gold, follows Chen Jimao. No minor coins.",
    wealth:"A+", mode:"buy", will_cn:"高", will_en:"High",
    coins:[
      { coin_id:"C005", cn:"户部壹两", grade:"", cost:"", current_est:"10,000,000+", acquired:"" },
      { coin_id:"C017", cn:"地球壹圆", grade:"MS62", cost:"1200万（陈吉茂处）", current_est:"2000万+", acquired:"" },
      { coin_id:"C006", cn:"张作霖十五年", grade:"", cost:"2600万", current_est:"1700万+", acquired:"" },
      { coin_id:null, cn:"孙像24年壹圆", grade:"", cost:"1000万（陈吉茂处）", current_est:"", acquired:"" },
      { coin_id:null, cn:"浙江七钱二分", grade:"", cost:"2000万", current_est:"", acquired:"" },
      { coin_id:null, cn:"喜敦老江南三钱六分", grade:"", cost:"", current_est:"", acquired:"" },
    ],
    network:["陈吉茂", "KL", "赵洋洋"],
    analysis_cn:"李广宏是当前市场最活跃的买家之一，出手大方。从陈吉茂处购入地球MS62（1200万）和孙像24年（1000万），张作霖成本2600万。总持仓超亿元。积极寻找新标的。",
    analysis_en:"Li Guanghong is one of the most active buyers in the market. Globe MS62 from Chen Jimao (12M), Sun Y24 (10M), Zhang Zuolin (26M). Total position >100M RMB. Actively seeking new acquisitions.",
  },
  {
    id:"COL03", cn:"重庆陶姐", en:"Tao Jie",
    loc_cn:"重庆", loc_en:"Chongqing", age:"50",
    bg_cn:"地产商，红美术馆。打算留给儿子。没有寿字双龙。觉得奉天买贵了。离婚分财产所得。",
    bg_en:"Real estate, Red Art Museum. Legacy for son. No Shou Zi. Felt overpaid for Fengtian. Divorce settlement funds.",
    wealth:"A", mode:"hold", will_cn:"低", will_en:"Low",
    coins:[
      { coin_id:"C005", cn:"户部壹两", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:"C002", cn:"奉天癸卯壹两", grade:"", cost:"高价", current_est:"4000万+", acquired:"" },
      { coin_id:"C006", cn:"张作霖十五年", grade:"AU53", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"张作霖十六年", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:"C019", cn:"金本位壹圆", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:"C017", cn:"地球壹圆", grade:"MS61", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"全套喜敦老江南", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"四川龙 / 珍珠龙", grade:"", cost:"", current_est:"", acquired:"" },
    ],
    network:["KL"],
    analysis_cn:"陶姐是女性顶级藏家中的代表人物。持有奉天壹两、户部壹两、金本位等重器，总持仓可能超2亿。但以传承为主，短期无出售意向。缺寿字双龙——这是她收藏的最大空白。",
    analysis_en:"Tao Jie is a representative female mega-collector. Holds Fengtian Tael, Hu Bu Tael, Gold Standard — total position possibly >200M RMB. Legacy-focused, unlikely to sell. Missing Shou Zi — her biggest gap.",
  },
  {
    id:"COL04", cn:"深圳赵勇", en:"Zhao Yong",
    loc_cn:"深圳", loc_en:"Shenzhen", age:"50+",
    bg_cn:"投资人，极其低调。只买不卖。",
    bg_en:"Investor, extremely private. Buy only, never sells.",
    wealth:"A+", mode:"buy", will_cn:"低", will_en:"Low (never sells)",
    coins:[
      { coin_id:"C005", cn:"户部壹两", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:"C017", cn:"地球壹圆", grade:"MS63+", cost:"", current_est:"5000万+", acquired:"" },
      { coin_id:"C006", cn:"张作霖十五年", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:"C018", cn:"本省", grade:"MS64", cost:"800万（CC处）", current_est:"2000万+", acquired:"2016" },
      { coin_id:null, cn:"云南春季", grade:"", cost:"", current_est:"", acquired:"" },
    ],
    network:["CC（周大为）", "KL"],
    analysis_cn:"赵勇可能是中国银圆收藏界最神秘的大藏家。只买不卖、极度低调。本省MS64以800万从CC处购入（2016），现估值超2000万。地球MS63+为该品种最高分之一。总持仓不可估量。",
    analysis_en:"Zhao Yong may be the most enigmatic mega-collector in Chinese numismatics. Buy only, ultra-private. Ben Sheng MS64 bought from CC for 8M (2016), now est. 20M+. Globe MS63+ is finest known. Total holdings incalculable.",
  },
  {
    id:"COL05", cn:"王中强", en:"Wang Zhongqiang",
    loc_cn:"浙江温州", loc_en:"Wenzhou", age:"",
    bg_cn:"强哥/小强。女儿出价买房，要移居美国。有出售意向。",
    bg_en:"'Qiang Ge'. Daughter buying house, emigrating to US. Willing to sell.",
    wealth:"A", mode:"sell", will_cn:"可能", will_en:"Possible",
    coins:[
      { coin_id:"C031", cn:"北洋壹两", grade:"MS62", cost:"100万美元", current_est:"开价1380万", acquired:"HS 2019?" },
      { coin_id:"C032", cn:"中字壹两", grade:"MS65", cost:"100万美元", current_est:"开价600万", acquired:"" },
      { coin_id:"C005", cn:"户部壹两", grade:"MS63", cost:"", current_est:"开价1000万", acquired:"" },
      { coin_id:"C020", cn:"签字大头", grade:"MS63", cost:"312万", current_est:"", acquired:"" },
      { coin_id:"C007", cn:"上海壹两", grade:"", cost:"1260万（HS 2022）", current_est:"开价1500万", acquired:"HS 2022" },
    ],
    network:["kent", "强"],
    analysis_cn:"王中强是当前市场最重要的潜在卖家。因女儿购房/移民美国，有明确出售动机。持有五大核心标的（户部、北洋、中字、签字大头、上海壹两），总报价超5000万。若他决定清仓，将为市场提供重大收购机会。",
    analysis_en:"Wang Zhongqiang is the most important potential seller in the current market. Clear motivation (daughter's house/emigration). Holds 5 core pieces totaling >50M in asking price. A liquidation event would create a major acquisition opportunity.",
  },
  {
    id:"COL06", cn:"李跃明", en:"Li Yueming",
    loc_cn:"香港/山东", loc_en:"HK/Shandong", age:"",
    bg_cn:"石油企业家。舒适区在1000-2000万/件。油生意不好。",
    bg_en:"Oil entrepreneur. Comfort zone 10-20M per piece. Oil business declining.",
    wealth:"A", mode:"buy", will_cn:"低", will_en:"Low",
    coins:[
      { coin_id:"C007", cn:"上海壹两", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"大尾龙", grade:"", cost:"HA25", current_est:"", acquired:"HA 2025" },
      { coin_id:"C010", cn:"老江南", grade:"MS66", cost:"1700万", current_est:"高峰2500万", acquired:"" },
      { coin_id:"C020", cn:"大头签字", grade:"MS64", cost:"", current_est:"", acquired:"" },
    ],
    network:["KL"],
    analysis_cn:"李跃明是香港/山东的石油企业家，在1000-2000万区间活跃。老江南MS66以1700万购入、高峰2500万——展示了顶级品的增值潜力。但油价下行影响其购买力。",
    analysis_en:"Li Yueming is an oil entrepreneur active in the 10-20M range. Old Jiangnan MS66 bought at 17M, peaked at 25M — showing appreciation potential. But declining oil prices affect his buying power.",
  },
  {
    id:"COL07", cn:"林宪璋", en:"Lin Xianzhang",
    loc_cn:"台湾", loc_en:"Taiwan", age:"50+",
    bg_cn:"投资人，出价凶狠。《机制币珍品集》作者。只买不卖。",
    bg_en:"Investor, aggressive bidder. Author of 'Pattern Coin Collection'. Buy only.",
    wealth:"A+", mode:"buy", will_cn:"高", will_en:"High",
    coins:[
      { coin_id:"C001", cn:"寿字双龙", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"湖南七钱二分", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"陕西七钱二分", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"黔宝", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"吉林厂平壹两", grade:"", cost:"", current_est:"", acquired:"" },
    ],
    network:[""],
    analysis_cn:"林宪璋是台湾最顶级的机制币藏家之一，持有八枚一级币，包括寿字双龙。出价凶狠、只买不卖，是拍场上最强劲的竞争者。任何寿字双龙上拍，他都会参与。",
    analysis_en:"Lin Xianzhang is one of Taiwan's top collectors, holding 8 Grade-1 coins including the Shou Zi. Extremely aggressive bidder, never sells. Any Shou Zi at auction, he will be in the room.",
  },
  {
    id:"COL08", cn:"张安生", en:"Zhang Ansheng",
    loc_cn:"澳门", loc_en:"Macau", age:"70",
    bg_cn:"老藏家，准备退出。银币不卖，但年事已高。",
    bg_en:"Veteran collector, preparing to exit. Won't sell silver, but aging.",
    wealth:"B+", mode:"hold", will_cn:"低（年事已高）", will_en:"Low (aging)",
    coins:[
      { coin_id:"C011", cn:"七三反版", grade:"", cost:"", current_est:"", acquired:"三套" },
      { coin_id:null, cn:"魏碑体", grade:"MS64", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"大清", grade:"", cost:"", current_est:"", acquired:"两枚" },
      { coin_id:null, cn:"张作霖", grade:"", cost:"", current_est:"", acquired:"" },
      { coin_id:null, cn:"湖南 / 陕西", grade:"", cost:"", current_est:"", acquired:"" },
    ],
    network:[""],
    analysis_cn:"张安生是澳门最重要的老藏家。持有三套七三反版（极罕）、魏碑体MS64、湖南、陕西等一级珍品。70岁高龄，虽声称不卖银币，但继承问题将迫使其藏品最终流入市场。关键监控对象。",
    analysis_en:"Zhang Ansheng is Macau's most important veteran collector. Holds 3 sets of 73 Reverse (extremely rare), Weibei MS64, Hunan, Shaanxi — Grade-1 pieces. At 70, inheritance considerations will eventually bring his collection to market. Key monitoring target.",
  },
  {
    id:"COL09", cn:"何代水", en:"He Daishui",
    loc_cn:"台湾/上海", loc_en:"Taiwan/Shanghai", age:"63",
    bg_cn:"半导体/IT行业高管，定居上海，儒雅。只买不卖。",
    bg_en:"Semiconductor/IT exec, Shanghai-based, refined. Buy only.",
    wealth:"A", mode:"buy", will_cn:"", will_en:"",
    coins:[{ coin_id:"C003", cn:"短须龙", grade:"", cost:"", current_est:"", acquired:"" }],
    network:[""],
    analysis_cn:"何代水是台湾半导体业的高管，定居上海。持有短须龙——宣三系列最珍版别之一。儒雅低调，只买不卖。科技新贵进入机制币收藏的代表人物。",
    analysis_en:"He Daishui is a Taiwan semiconductor executive based in Shanghai. Holds the Short Beard Dragon — one of the rarest Xuan Tong 3 varieties. A representative of tech wealth entering Chinese numismatics.",
  },
  {
    id:"COL10", cn:"周大为 (CC)", en:"Zhou Dawei (CC)",
    loc_cn:"上海", loc_en:"Shanghai", age:"85年生",
    bg_cn:"加拿大籍二代，art021创始人。藏品鼎盛时期估值超20亿。为公司上市已基本出清。",
    bg_en:"Canadian-born 2nd gen, art021 founder. Collection peaked at 2B+ RMB. Substantially liquidated for IPO.",
    wealth:"S", mode:"liquidated", will_cn:"出清", will_en:"Liquidated",
    coins:[
      { coin_id:"C018", cn:"本省 MS64", grade:"MS64", cost:"", current_est:"", acquired:"已出售给赵勇（800万）" },
      { coin_id:"C005", cn:"户部壹两", grade:"", cost:"", current_est:"", acquired:"已出售" },
      { coin_id:null, cn:"七三反版三套", grade:"", cost:"", current_est:"", acquired:"已出售" },
      { coin_id:null, cn:"金本位壹圆", grade:"", cost:"", current_est:"", acquired:"已出售" },
      { coin_id:null, cn:"宣三长须龙/短须龙", grade:"", cost:"", current_est:"", acquired:"已出售" },
      { coin_id:null, cn:"喜敦老江南全套", grade:"", cost:"", current_est:"", acquired:"已出售" },
    ],
    network:["深圳赵勇", "KL"],
    analysis_cn:"周大为（CC）是中国银圆收藏史上最大的单一藏家之一。藏品若不出售估值20亿人民币。但为公司上市已大量清仓——本省MS64（800万）卖给深圳赵勇即为一例。其清仓行为深刻改变了市场格局。",
    analysis_en:"Zhou Dawei (CC) is one of the largest single collectors in Chinese numismatic history. Collection estimated at 2B RMB if intact. Major liquidation for IPO — selling Ben Sheng MS64 (8M) to Zhao Yong is one example. His selloff fundamentally reshaped the market.",
  },
  {
    id:"COL11", cn:"陈吉茂", en:"Chen Jimao",
    loc_cn:"台湾/上海", loc_en:"Taiwan/Shanghai", age:"",
    bg_cn:"定居上海，近年偏好瓷器。会卖但价格高。",
    bg_en:"Shanghai-based, shifted to porcelain. Sells at premium.",
    wealth:"A", mode:"sell", will_cn:"低", will_en:"Low (premium prices)",
    coins:[],
    network:["李广宏", "KL", "HA"],
    analysis_cn:"陈吉茂是连接台湾和大陆收藏圈的关键人物。地球MS62以1200万卖给李广宏，孙像24年以1000万卖给李广宏。近年转向瓷器收藏，银圆虽会出售但要价极高。",
    analysis_en:"Chen Jimao is a key bridge between Taiwan and mainland collecting circles. Sold Globe MS62 (12M) and Sun Y24 (10M) to Li Guanghong. Shifting to porcelain but sells silver at premium.",
  },
];

// Export for use
if (typeof module !== 'undefined') module.exports = { COINS, AUCTION_RECORDS, COLLECTORS };
